export const tables = [
  {
    id: "table1",
    name: "Table 1",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table2",
    name: "Table 2",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table3",
    name: "Table 3",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table4",
    name: "Table 4",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table5",
    name: "Table 5",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table6",
    name: "Table 6",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table7",
    name: "Table 7",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table8",
    name: "Table 8",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table9",
    name: "Table 9",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
  {
    id: "table10",
    name: "Table 10",
    columns: [
      { column_id: "col1", name: "Column 1", column_data_type: "string" },
      { column_id: "col2", name: "Column 2", column_data_type: "number" },
      { column_id: "col3", name: "Column 3", column_data_type: "string" },
      { column_id: "col4", name: "Column 4", column_data_type: "number" },
      { column_id: "col5", name: "Column 5", column_data_type: "string" },
      { column_id: "col6", name: "Column 6", column_data_type: "number" },
      { column_id: "col7", name: "Column 7", column_data_type: "string" },
      { column_id: "col8", name: "Column 8", column_data_type: "number" },
      { column_id: "col9", name: "Column 9", column_data_type: "string" },
      { column_id: "col10", name: "Column 10", column_data_type: "number" },
      { column_id: "col11", name: "Column 11", column_data_type: "string" },
      { column_id: "col12", name: "Column 12", column_data_type: "number" },
    ],
  },
];
